### ISSUE TITLE
Beta test feedback

### ISSUE THREAD

**Issue by NateWr** [scottopolis/edd-metrics#5]
Hi Scott, just did a quick beta test on a slightly old staging site I've got (last sale in db was mid-June, first sale was 2012-ish). I ran into a few issues with data not displaying.

Here I chose "last year" and it's returning no sales info. If I choose last six months or a shorter time span it seems to show correctly.

![selection_039](https://cloud.githubusercontent.com/assets/2306629/17887275/9e78b86c-691d-11e6-8d14-5cf3dfc7fcb2.png)

I could never get the earnings by download graph to load, no matter what time range I selected.

![selection_038](https://cloud.githubusercontent.com/assets/2306629/17887317/cceefc60-691d-11e6-8ad9-dffa06a11ac2.png)

When selecting All Time on the Revenue Detail page I get a JS error and the graph never loads. Here it is:

![selection_037](https://cloud.githubusercontent.com/assets/2306629/17887369/087c05c0-691e-11e6-92fa-8c6b2635e1ac.png)

I've worked with chartjs a bit before and I believe this is caused when any data set is missing a label. I think each data set needs a label, if I am recalling correctly.

The plugin looks great. I'm particularly interested in the breakdown of earnings by download over time. A big feature request for me would be the ability to see earnings over time for groups of downloads. 

For instance, I sell plugins and themes. I'd love to be able to see earnings for _all_ themes or _all_ plugins. Also, I sell plugins as addons for two different base plugins. So it'd be great to be able to just arbitrarily group downloads and say, "how much did this group earn in total?".

Other metrics that would be interesting: number of downloads per cart, lots more specifically on license renewals, a list of high-value customers. Just throwing these out there, I'm sure you've got plenty of your own ideas. :+1:

**Comment by scottopolis** [comment]
Hey Nate, thanks for your feedback.  The previous year stats should be fixed in 03815bed58e4fc863a0a7b3f072342d74be9824a

The single product pie chart uses 'post_type' => 'download', the only thing I can think of is maybe you changed the slug?

I definitely want to do more data on individual products, hopefully I have time.

**Comment by NateWr** [comment]
Ah you know what, the single pie chart is probably because I'm using this plugin:

https://en-gb.wordpress.org/plugins/edd-hide-download/

**Comment by NateWr** [comment]
Hmm, no that's not it. I just tested deactivating that plugin but I still get the missing label error.

I haven't changed the download's post type slug. If I get some time I'll try to play around with deactivating plugins to see if I can find a conflict.

**Comment by scottopolis** [comment]
Ok cool. I'm not seeing this issue on any of my sites, so hard to fix if I can't replicate.

I just pushed a bunch of updates to master, you may also want to update and maybe it got fixed by accident :)

**Comment by brianhogg** [comment]
I also can't get the graph to load with the same error (I just grabbed the zip yesterday) on the "revenue details" page:

<img width="1219" alt="screenshot 2016-08-25 11 33 12" src="https://cloud.githubusercontent.com/assets/627497/17975481/e084c0ca-6ab7-11e6-8753-d98499413fa8.png">

Perhaps because it's a staging site without a lot of the sales data brought over? (ie. hasn't pulled sales data in the last 3-4 months)

Also getting a fun % increase number (again limited sales data may be the cause):

<img width="308" alt="screenshot 2016-08-25 11 32 03" src="https://cloud.githubusercontent.com/assets/627497/17975577/41486182-6ab8-11e6-90a9-1eea7eeb2f09.png">

**Comment by scottopolis** [comment]
Hmm, things definitely get weird when there's a lot of zeros. The missing labels error may have to do with that.

**Comment by scottopolis** [comment]
Hey guys, have you tried 0.3 yet? Wondering if it fixes these issues.

**Comment by brianhogg** [comment]
I tested it with more data from a fresher export so not sure if it's fixed issues with lots of zeros, but does seem to be working nicely!

**Comment by scottopolis** [comment]
Ok closing this, feel free to report more issues in new tickets.
